# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: cd backend && go mod init github.com/kh3rld/e-waste-soko && cd cmd go build -v 

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
          go-version-file: go.mod

    - name: Install dependencies
      run: go mod tidy